#!/bin/sh

GTKRCFILEPATH=$(awk -F "=" '/gtk-theme-name/ {print $2}' ~/.gtkrc-2.0 | tr -d '"')
SELECTEDCOLOR=$(cat ~/.themes/$GTKRCFILEPATH/gtk-2.0/gtkrc | grep selected_bg | cut -d':' -f2 | sed 's/[ "]//g')

SB=$SELECTEDCOLOR
SF="#ffffff"
NB="#181818"
NF="#ffffff"
