#!/bin/sh
# 
# Furry Fetch - tiny system info for Debian and Debian-like OS
# Fork of ufetch that's I found there: https://github.com/ix/bin/blob/master/ufetch
# ASCII art -=[ dog paws ]=- by jgs (http://www.retrojunkie.com/asciiart/animals/pawprint.htm)
#

## INFO

# user is already defined
HOST="$(hostname)"
OS="$(lsb_release -d | sed 's/Description://g;s/^[ \t]*//')"
KERNEL="$(uname -sr)"
UPTIME="$(uptime -p | sed s:"up "::)"
PACKAGES="$(dpkg --get-selections | wc -l)"
WM="$(wmctrl -m | head -n1 | sed 's/Name://g;s/^[ \t]*//')"

## DEFINE COLORS

# probably don't change these
bc="$(tput bold)"	# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"	# reset

# you can change these
lc="${bc}${c6}"		# labels
nc="${bc}${c6}"		# user and hostname
tc="${bc}${c7}"		# text
pc="${c6}"		# penguin

## OUTPUT

#cat $HOME/furr

cat <<EOF
                 .-.   .-.	   ${lc}${USER}${rc}${tc}@${rc}${nc}${HOST}${rc}
                /   \ /   \        ${lc}OS:${rc}       ${tc}${OS}${rc}
            .-. |    |    | .-.    ${lc}KERNEL:${rc}   ${tc}${KERNEL}${rc}
           /   \ \  / \  / /   \   ${lc}UPTIME:${rc}   ${tc}${UPTIME}${rc}
           |   |  '\`.-.\`'  |   |   ${lc}PACKAGES:${rc} ${tc}${PACKAGES}${rc}
            \_.' .-\`   \`-. '._/    ${lc}SHELL:${rc}    ${tc}${SHELL}${rc}
              .-'         '-.      ${lc}WM:${rc}       ${tc}${WM}${rc}
             /               \\
             |               |
              \             /
               '.___...___.'
EOF
