#!/usr/bin/env bash

# how long should the popup remain?
duration=1.1

# define geometry
barw=300
barh=35
barx=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d'x' -f1)
bary=$(xdpyinfo | awk '/dimensions/ {print $2}' | cut -d'x' -f2)
let barx=${barx}/2-${barw}/2
#let bary=${bary}/2-${barh}/2
let bary=40

# colors
bar_bg='#64000000'
bar_fg='#ffffffff'

# font used
bar_font_1='Dejavu Sans-16'
bar_font_2='FontAwesome-16'
# compute all this
baropt="-d -g ${barw}x${barh}+${barx}+${bary} -f ${bar_font_1} -o 2 -f ${bar_font_2} -F${bar_fg} -B${bar_bg}"

#Create the popup and make it live for 3 seconds
(echo -e "${1}"; sleep ${duration}) | lemonbar ${baropt}
