#!/bin/bash

TIME=30	 	#Second (s), minute (m), days (d). By default - 30m (minutes). 
			#For me, don't work, so I use "let" (see bottom).
FOLDER="$HOME/Wallpapers/"
CONFIG="$HOME/.config/nitrogen/bg-saved.cfg"

let "T = $TIME*60" 	#convert minutes to seconds for sleep

ERRORNOTFOUND="-1"	#folder not found error
ERRORNOIMAGES="-2"	#folder is empty error

function errorhandle()
{
	if [ ! -d $FOLDER ]; then
		echo "error: $ERRORNOTFOUND folder not found"
		exit
	elif [[ `ls $FOLDER` == "" ]]; then
		echo "error: $ERRORNOIMAGES $FOLDER don't containg any files"
		exit
	fi
}

function rand()
{
	set -- `ls $FOLDER`
	
	#need, cuz' ls generate one extra string
	tmp=`ls -l $FOLDER | wc -l`
	let "m = $tmp - 1"
	
	random=$(shuf -i 1-$m -n 1)
	
	sed -i "2d" $CONFIG
	sed -i -e "2ifile=$FOLDER${!random}" $CONFIG
	
	nitrogen --restore
}

function go()
{
	errorhandle
	touch /tmp/.randomwallpaper		#lock file
	while true; do
		sleep $T
		
		if [ ! -f /tmp/.randomwallpaper ]; then
			break
			exit
		fi
		
		rand
	done
}

function help()
{
echo -e "
 Random wallpaper for Nitrogen. (c) 2015 Volk_Milit
 This program is free software: you can redistribute it and/or modify
 it under the terms of the Apache v2.0 License 
 (see http://www.apache.org/licenses/LICENSE-2.0).
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 Apache v2.0 License for more details.
    
 Useful command:
 --next: Next wallpaper
 --exit: Delete lock file. But script may still execute, if timer != 0
 "
}

if [ "$1" = "--next" ]; then
	rand
	exit
elif [ "$1" = "--exit" ]; then
	rm /tmp/.randomwallpaper
elif [ "$1" = "--help" ]; then
	help
else
	go
fi
