#!/bin/sh
# end a command with ; to run in a terminal

. lib/colors

TEXT="run:"
FN="-*-fixed-medium-r-dejavu-*-16-*-*-*-*-*-iso10646-*"
OPTIONS="-o .90 -nf $FN -nb $NB -nf $NF -sb $SB -sf $SF -x $((1280/2-800/2)) -y 40 -w 800 -l 15 -p $TEXT -i -h 30"

DMENU="dmenu_run -i $OPTIONS"
TERMI="st -e"
#CACHE="$HOME/.cache/dmenu_cache_recent"

#[ -f $CACHE ] && touch $CACHE

#MOST_USED=`sort $CACHE | uniq -d | sort -r`
#RUN=`(echo "$MOST_USED"; dmenu_path | grep -vxF "$MOST_USED") | $DMENU $@` &&
#(echo $RUN; head -n 99 $CACHE) > $CACHE.$$ &&
#mv $CACHE.$$ $CACHE

RUN=$($DMENU $@)

case $RUN in
    *\;) exec `echo $TERMI $RUN | sed -e 's/;$//'`;;
    *)   exec $RUN;;
esac

exit 0
