#!/bin/sh

FOLDER="$HOME/Изображения/screenshots/"
img=$FOLDER$(date +%F-%T).png
basic_opt="-trim -strip -silent"

shot()
{
	import $basic_opt -window root $FOLDER$(date +%F-%T).png
}

active()
{
	wid=$(xprop -root | grep _NET_ACTIVE_WINDOW\(WINDOW\) | cut -d'#' -f2)
	import $basic_opt -window $wid -frame -border $FOLDER$(date +%F-%T).png
}

sel()
{
	slop_opt="slop -l -c 1,0.7,0.0,0.3"
	
	eval $(slop $slop_opt)
	[ "$G" = "0x0+0+0" ] && exit

	import $basic_opt -window root -crop $G $img
}

if [ "$1" = "-s" ]; then
	sel
elif [ "$1" = "-m" ]; then
	menu
elif [ "$1" = "-u" ]; then
	active
else
	shot	
fi

[ -f "$img" ] && notify-send Scrot "Screenshot saved" & xclip -selection clip -t image/png $img

exit 0
