#!/bin/sh

# z3bra - (c) wtfpl 2014

usage () {
    cat <<EOF
usage: $(basename $0) [-hsl] [-+!]
    -h : print help
    -s : print on/off
    -l : print the current volume percentage (default)
     + : volume +5%
     - : volume -5%
     ! : toggle mute
EOF
}

level() {
    echo `pactl list sinks | awk '/Громкость:/{print $5}' | head -1`
}

state() {
    amixer sget Master | awk 'NR==7 {print $6}'
}

lset() {
	pactl set-sink-volume @DEFAULT_SINK@ $1% &
	vol #& aplay /home/volk/.local/share/sounds/vol.wav
}

sset() {
	amixer set Master toggle & vol
}

# print out level and state if no argument is given
test $# -eq 0 && echo "`level`" && exit 0

case $1 in
    -h)        usage ;;
    -s)        state ;;
    -l)        level ;;
     up|+)	lset +5;;
     down|-)   lset -5;;
     toggle|!) sset	;;
     *)        usage
esac
